spring:
  application:
    name: mensageria
  jpa:
    show-sql: true
    generate-ddl: true

# Rabbitmq connection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Queue names
rabbitmq:
  queues: 
    default: default-queue
    direct-1: direct-queue-1
    direct-2: direct-queue-2
    fanout-1: fanout-queue-1
    fanout-2: fanout-queue-2
    topic-1: topic-queue-1
    topic-2: topic-queue-2
    topic-3: topic-queue-3

  direct: 
    exchange: direct-exchange # Exchange proprieties
    # Routing keys
    routing-key-1: direct-routing-key-1
    routing-key-2: direct-routing-key-2

  fanout:
    exchange: fanout-exchange
  
  # patterns
  # (*) means; one word ban be replaceable with (*)
  # (#) means; zero or more words can replaceable with (#)
  topic:
    exchange: topic-exchange
    pattern-1: '*.topic.*'
    pattern-2: first.topic.#
    pattern-3: second.topic.*

