spring:
  application:
    name: mensageria
  jpa:
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  queues: 
    default: default